### ISSUE TITLE
Definition of 'abbreviated injury scale training course plan specification' is unclear

### ISSUE THREAD

**Issue by jonathanbona** [OOSTT/OOSTT#11]
"A plan specification that specifies the content, methodology, and evaluation of **a training course to the Abbreviated Injury Scale**, informs about coding rules and conventions, and discusses methods for assessing the multiple injury patient."

The part in bold is a little difficult to parse. Is this a training course to teach the AIS?

**Comment by mbrochhausen** [comment]
edited definition and clarified it:
https://github.com/OOSTT/OOSTT/commit/7a4684818a521a9916f1ea0343c45344e78736a5
jonathanbona: take a look at close, if you find it appropriate.

**Comment by jonathanbona** [comment]
Looks good to me
