### ISSUE TITLE
Use of wrong PURLs

### ISSUE THREAD

**Issue by matentzn** [OOSTT/OOSTT#14]
http://purl.org/obo/owl/PATO#PATO_0001025

see also:
https://github.com/DIDEO/DIDEO/issues/16

Some more context for the ticket: https://github.com/orgs/OBOFoundry/projects/5

**Comment by mbrochhausen** [comment]
Thanks for finding this. I’ll take care of it ASAP.

**Comment by mbrochhausen** [comment]
This was due to an import from PNO, an ontology OOSTT imports. The problem has been addressed in PNO and resolved without a new commit to OOSTT.
