### ISSUE TITLE
'governmental organization' (OOSTT:00000111) has no definition

### ISSUE THREAD

**Issue by jmwhorton** [OOSTT/OOSTT#19]

**Comment by jmwhorton** [comment]
Hello @neilotte, 
@mbrochhausen  asked me to reach out to you and assign this issue since you were listed as term editor for 'governmental organization.'  We were unsure of the intended meaning and need your input for a definition.  Thanks.

**Comment by neilotte** [comment]
@jmwhorton @mbrochhausen Thanks for the ping here. I think the goal was to establish a contrast class with nongovernmental organization. This will involve some modest hierarchy updates. I've open a pull request for you review. Thanks!

**Comment by jmwhorton** [comment]
Updated and resolved with https://github.com/OOSTT/OOSTT/pull/21
