### ISSUE TITLE
'employment contract document act' should output roles

### ISSUE THREAD

**Issue by jonathanbona** [OOSTT/OOSTT#7]
'employment contract document act' http://purl.obolibrary.org/obo/OOSTT_00000190 should have specified outputs:

- OMRSE: 'employer role': http://purl.obolibrary.org/obo/OMRSE_00000087
- OMRSE: 'employee role': http://purl.obolibrary.org/obo/OMRSE_00000077

**Comment by mbrochhausen** [comment]
Done: https://github.com/OOSTT/OOSTT/commit/0717908d42b728007b552e84b08aaa5009de0068
